spring.application.name=backend

spring.main.banner-mode=off
spring.main.log-startup-info=false

# Logging config
logging.file.name=codelessdb.log 
logging.file.path=./backend/src/main/resources
# logging.level.root=DEBUG