spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/codelessdb
spring.datasource.username=root
spring.datasource.password=Lamar_238
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true